services:
  dwh-crm-erp:
    container_name: dwh-crm-erp_container
    image: postgres:13-alpine
    hostname: ${POSTGRES_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5434:5432
    volumes:
      - "./postgres_init_db:/docker-entrypoint-initdb.d"
      - "./input_data:/home/input_data:rw"
      - "../psql_vol:/var/lib/postgresql/data:rw"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 900s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - my_network

networks:
  my_network:
