
etl-with-dbt-dwh:
  outputs:
    dev:
      dbname: "{{ env_var('POSTGRES_DB') }}" # uses jinja template so needs env_var
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      schema: bronze
      threads: 2
      type: postgres
  target: dev
