dbt_transform_postgres:
  target: dev
  outputs:
    dev:
      dbname: "{{ env_var('POSTGRES_DB') }}" # uses jinja template so needs env_var
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5434
      schema: bronze
      threads: 2
      type: postgres

dbt_duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_PATH') }}"
      threads: 2
