etl-with-dbt-dwh_postgres:
  outputs:
    dev:
      dbname: "{{ env_var('POSTGRES_DB') }}" # uses jinja template so needs env_var
      host: "{{ env_var('POSTGRES_HOST') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      schema: bronze
      threads: 2
      type: postgres
  target: dev

etl-dbt-duckdb:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "/Users/dross/Desktop/educ/etl_with_dbt_dwh/dwh.duckdb"
      threads: 2
