version: 2

sources:
  - name: analytics_source
    schema: "gold" # Enclose in quotes
    tables:
      - name: "dim_customers_current" # Enclose in quotes
      - name: "dim_products_current" # Enclose in quotes
      - name: "fact_sales" # Enclose in quotes

models:
  - name: copy_gold_tables
    description: "Syncs gold-layer tables from PostgreSQL to DuckDB by invoking the 'copy_all_from_postgres_gold' macro."
  - name: report_customers
    description: "Generates a comprehensive customers report."
  - name: report_products
    description: "Generates a comprehensive products report."
