version: 2

sources:
  - name: analytics_source
    schema: "gold" # Enclose in quotes
    tables:
      - name: "dim_customers_current" # Enclose in quotes
      - name: "dim_products_current" # Enclose in quotes
      - name: "fact_sales" # Enclose in quotes

models:
  - name: report_customers
    description: "Generates a comprehensive customers report."
  - name: report_products
    description: "Generates a comprehensive products report."
