/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
- To quantify data and group results by specific dimensions.
- For understanding data distribution across categories.

SQL Functions Used:
- Aggregate Functions: SUM(), COUNT(), AVG()
- GROUP BY, ORDER BY
===============================================================================
 */
ATTACH 'dwh.duckdb' AS db1;

-- Find total customers by countries
SELECT
    --'total_customer_per_country' as measure_name,
    customer_country,
    COUNT(customer_key) AS total_customer_by_country
FROM
    gold.dim_customers
GROUP BY
    customer_country
ORDER BY
    total_customer_by_country desc;

/*
customer_country,total_customer_by_country
United States,7482
Australia,3591
United Kingdom,1913
France,1810
Germany,1780
Canada,1571
n/a,337
 */
-- Find total customers by gender per country
SELECT
    customer_gender,
    customer_country,
    COUNT(customer_key) AS total_customer_by_gender_country
FROM
    gold.dim_customers
GROUP BY
    customer_gender,
    customer_country
ORDER BY
    total_customer_by_gender_country desc;

/*
customer_gender,customer_country,total_customer_by_gender_country
Male,United States,3757
Female,United States,3724
Male,Australia,1814
Female,Australia,1777
Male,United Kingdom,977
Female,United Kingdom,932
Male,France,913
Male,Germany,903
Female,France,891
Female,Germany,873
Male,Canada,804
Female,Canada,767
Male,n/a,173
Female,n/a,164
n/a,France,6
n/a,United Kingdom,4
n/a,Germany,4
n/a,United States,1
 */
-- Find total products by category
SELECT
    product_category,
    COUNT(product_key) AS total_products_by_category
FROM
    gold.dim_products
GROUP BY
    product_category
ORDER BY
    total_products_by_category desc;

/*
product_category,total_products_by_category
Components,127
Bikes,97
Clothing,35
Accessories,29
null,7
 */
-- What is the average costs in each category?
SELECT
    product_category,
    ROUND(AVG(product_cost), 2) AS avg_product_cost
    --count(product_key) as total_products_by_category
FROM
    gold.dim_products
GROUP BY
    product_category
ORDER BY
    avg_product_cost desc;

-- What is the total revenue generated for each category?
SELECT
    dp.product_category,
    AVG(dp.product_cost) AS avg_product_cost_per_category,
    SUM(fs.sales_amount) AS total_revenue_per_category
FROM
    gold.fact_sales fs
    LEFT JOIN gold.dim_products dp ON fs.product_key = dp.product_key
GROUP BY
    dp.product_category
ORDER BY
    total_revenue_per_category desc;

/*
product_category,avg_product_cost_per_category,total_revenue_per_category
Bikes,1131.6479447550148,28316272
Accessories,7.222015959215339,700262
Clothing,22.29271508625426,339716
 */
-- What is the total revenue generated by each customer?
SELECT
    dc.customer_key,
    SUM(fs.sales_amount) AS top_10_customers
FROM
    gold.fact_sales fs
    LEFT JOIN gold.dim_customers dc ON fs.customer_key = dc.customer_key
GROUP BY
    dc.customer_key
ORDER BY
    top_10_customers desc
LIMIT
    10;

/*
customer_key,total_revenue_per_customer
AW00012301,13294
AW00012132,13294
AW00012308,13268
AW00012131,13265
AW00012300,13242
AW00012321,13215
AW00012124,13195
AW00012307,13172
AW00012296,13164
AW00011433,12914

 */
-- What is the distribution of sold items across countries?
SELECT
    dc.customer_country,
    --dp.product_name,
    SUM(fs.sales_quantity) AS total_sold_items
FROM
    gold.fact_sales fs
    LEFT JOIN gold.dim_customers dc ON fs.customer_key = dc.customer_key
    LEFT JOIN gold.dim_products dp ON fs.product_key = dp.product_key
GROUP BY
    dc.customer_country --,dp.product_name
ORDER BY
    total_sold_items desc;

/*
customer_country,total_sold_items
United States,20481
Australia,13346
Canada,7630
United Kingdom,6910
Germany,5626
France,5559
n/a,871

 */
DETACH db1;