services:
  postgres:
    container_name: astro-airflow-postgres-metadata
    image: postgres:15-alpine
    networks:
      - bike_insights_network # needed for all services to share the same network

  scheduler:
    volumes:
      - ../warehouse/input_data:/usr/local/airflow/input_data:rw
    networks:
      - bike_insights_network

  dag-processor:
    volumes:
      - ../warehouse/input_data:/usr/local/airflow/input_data:rw
    networks:
      - bike_insights_network

  triggerer:
    volumes:
      - ../warehouse/input_data:/usr/local/airflow/input_data:rw
    networks:
      - bike_insights_network

networks:
  bike_insights_network:
    name: bike_insights_network
    external: true
