/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
select
    --'total_customer_per_country' as measure_name,
    customer_country,
    count(customer_skey) as total_customer_by_country
from {{ source('analytics_source', 'dim_customers_current') }} -- gold.dim_customers
group by customer_country
order by total_customer_by_country desc;

/*
customer_country,total_customer_by_country
United States,7482
Australia,3591
United Kingdom,1913
France,1810
Germany,1780
Canada,1571
n/a,337
 */

-- Find total customers by gender per country
select
    customer_gender, customer_country,
    count(customer_skey) as total_customer_by_gender_country
from {{ source('analytics_source', 'dim_customers_current') }}--gold.dim_customers
group by customer_gender, customer_country
order by total_customer_by_gender_country desc;

/*
 customer_gender,customer_country,total_customer_by_gender_country
Male,United States,3757
Female,United States,3724
Male,Australia,1814
Female,Australia,1777
Male,United Kingdom,977
Female,United Kingdom,932
Male,France,913
Male,Germany,903
Female,France,891
Female,Germany,873
Male,Canada,804
Female,Canada,767
Male,n/a,173
Female,n/a,164
n/a,France,6
n/a,United Kingdom,4
n/a,Germany,4
n/a,United States,1
 */

-- Find total products by category
select
    product_category,
    count(product_skey) as total_products_by_category
from {{ source('analytics_source', 'dim_products_current') }}--gold.dim_products
group by product_category
order by total_products_by_category desc;

/*
 product_category,total_products_by_category
Components,127
Bikes,97
Clothing,35
Accessories,29
null,7
 */
-- What is the average costs in each category?
select
    product_category,
    round(avg(product_cost),2) as avg_product_cost
    --count(product_skey) as total_products_by_category
from {{ source('analytics_source', 'dim_products_current') }} --gold.dim_products
group by product_category
order by avg_product_cost desc;

-- What is the total revenue generated for each category?
Select
    dp.product_category,
    avg(dp.product_cost) as avg_product_cost_per_category,
    sum(fs.sales_amount) as total_revenue_per_category
from {{ source('analytics_source', 'fact_sales') }} --gold.fact_sales fs
left join {{ source('analytics_source', 'dim_products_current') }} dp on fs.product_skey=dp.product_skey
group by dp.product_category
order by total_revenue_per_category desc;

/*
 product_category,avg_product_cost_per_category,total_revenue_per_category
Bikes,1131.6479447550148,28316272
Accessories,7.222015959215339,700262
Clothing,22.29271508625426,339716
 */

-- What is the total revenue generated by each customer?
Select
    dc.customer_key,
    sum(fs.sales_amount) as top_10_customers
from {{ source('analytics_source', 'fact_sales') }} fs
left join {{ source('analytics_source', 'dim_customers_current') }} dc on fs.customer_skey=dc.customer_skey
group by dc.customer_key
order by top_10_customers desc
limit 10;

/*
customer_key,total_revenue_per_customer
AW00012301,13294
AW00012132,13294
AW00012308,13268
AW00012131,13265
AW00012300,13242
AW00012321,13215
AW00012124,13195
AW00012307,13172
AW00012296,13164
AW00011433,12914

 */

-- What is the distribution of sold items across countries?
Select
    dc.customer_country,
    --dp.product_name,
    sum(fs.sales_quantity) as total_sold_items
from {{ source('analytics_source', 'fact_sales') }} fs
left join {{ source('analytics_source', 'dim_customers_current') }} dc on fs.customer_skey=dc.customer_skey
left join {{ source('analytics_source', 'dim_products_current') }} dp on fs.product_skey=dp.product_skey
group by dc.customer_country--,dp.product_name
order by total_sold_items desc;

/*
 customer_country,total_sold_items
United States,20481
Australia,13346
Canada,7630
United Kingdom,6910
Germany,5626
France,5559
n/a,871

 */
